import nextcord
import os
import aiohttp
import time
import base64

from nextcord.ext import commands
from PIL import Image
from io import BytesIO
from dotenv import load_dotenv

load_dotenv()
p = os.getenv("PREFIX")

class Dropdown(nextcord.ui.Select):
    def __init__(self, message, images, user):
        self.message = message
        self.images = images
        self.user = user

        options = [
            nextcord.SelectOption(label="1"),
            nextcord.SelectOption(label="2"),
            nextcord.SelectOption(label="3"),
            nextcord.SelectOption(label="4"),
            nextcord.SelectOption(label="5"),
            nextcord.SelectOption(label="6"),
            nextcord.SelectOption(label="7"),
            nextcord.SelectOption(label="8"),
            nextcord.SelectOption(label="9"),
        ]

        super().__init__(
            placeholder="Choose one of the 9 images you want to see!",
            min_values=1, 
            max_values=1, 
            options=options
            )

    async def callback(self, interaction: nextcord.Interaction):
        if not int(self.user) == int(interaction.user.id):
            await interaction.response.send.message("You did not request this image!", ephemeral=True)
        selection = int(self.values[0])-1
        image = BytesIO(base64.decodebytes(self.images[selection].encode("utf-8")))
        return await self.message.edit(content="Content Generated by **craiyon.com** check out the site to try it out yourself!", file=nextcord.File(image, "genImage.png"), view=DropdownView(self.message, self.images, self.user))

class DropdownView(nextcord.ui.View):
    def __init__(self, message, images, user):
        super().__init__()
        self.message = message
        self.images = images
        self.user = user
        self.add_item(Dropdown(self.message, self.images, self.user))

class Fun(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.Cog.listener()
    async def on_ready(self):
        print("Fun Cog is ready!")

    @commands.command()
    async def generate(self, ctx: commands.Context, *, prompt: str):
        ETA = int(time.time() + 60)
        msg = await ctx.send(f"Please be patient, this image takes time:wink:. ETA: <t:{ETA}:R>")
        async with aiohttp.request("POST", "https://backend.craiyon.com/generate", json={"prompt": prompt}) as resp:
            r = await resp.json()
            images = r['images']
            image = BytesIO(base64.decodebytes(images[0].encode("utf-8")))
            return await msg.edit(content="Content Generated by **craiyon.com** check out the site to try it out yourself!", file=nextcord.File(image, "genImage.png"), view=DropdownView(msg, images, ctx.author.id))

    @commands.group()
    async def fun(self, ctx):
        pass

    @fun.command()
    async def help(self, ctx):
        em = nextcord.Embed(title="Fun Help", description="All Fun Commands", color=nextcord.Color.blue())
        em.add_field(name="**Generate**", value=f"{p}generate <prompt>", inline=False)
        em.set_footer(text="More commands will be added soon!")
        await ctx.send(embed=em)

        

def setup(bot):
    bot.add_cog(Fun(bot))

